/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"C:\ti\simplelink_cc26x2_sdk_2_30_00_34\source\ti\ble5stack\blelib\cc26x2r1\ctrl\hci_pxxx.a"
"C:\ti\simplelink_cc26x2_sdk_2_30_00_34\source\ti\ble5stack\blelib\cc26x2r1\ctrl\ll_pxxx.a"
"C:\ti\simplelink_cc26x2_sdk_2_30_00_34\source\ti\ble5stack\blelib\cc26x2r1\hci_tl\hci_tl_none.a"
"C:\ti\simplelink_cc26x2_sdk_2_30_00_34\source\ti\ble5stack\blelib\cc26x2r1\host\att_pxxx_coc.a"
"C:\ti\simplelink_cc26x2_sdk_2_30_00_34\source\ti\ble5stack\blelib\cc26x2r1\host\gap_pxxx_coc.a"
"C:\ti\simplelink_cc26x2_sdk_2_30_00_34\source\ti\ble5stack\blelib\cc26x2r1\host\gatt_pxxx_coc.a"
"C:\ti\simplelink_cc26x2_sdk_2_30_00_34\source\ti\ble5stack\blelib\cc26x2r1\host\l2cap_pxxx_coc.a"
"C:\ti\simplelink_cc26x2_sdk_2_30_00_34\source\ti\ble5stack\blelib\cc26x2r1\host\profiles_pxxx_coc.a"
"C:\ti\simplelink_cc26x2_sdk_2_30_00_34\source\ti\ble5stack\blelib\cc26x2r1\host\smp_pxxx_coc.a"
"C:\ti\simplelink_cc26x2_sdk_2_30_00_34\source\ti\ble5stack\blelib\cc26x2r1\host\sm_pxxx_coc.a"
